[package]
name = "plots"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-iter = "1.2.0"
chrono = "0.4.38"
csv = "1.3.0"
csv-sniffer = "0.3.1"
eframe = "0.28.1"
egui_plot = "0.28.1"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
enumflags2 = "0.7.10"
once_cell = "1.20.2"
regex = "1.11.1"
